### ISSUE TITLE
PyCraft_tut_7 terrain generation is kinda glitched......

### ISSUE THREAD

**Issue by HeyItsAnushtubh** [RedHenDev/python#1] opened 2021-07-18 09:57 UTC
![image](https://user-images.githubusercontent.com/87482637/126062869-446a3858-5373-4aac-9b61-ee4dad0ea773.png)
Hey, (umm idk ur name).... @RedHenDev 

Can you tell what's happening?
I tried to code it myself i got the same output. So I decided to use you code and ....... you guessed it , same glitched terrain.
I just downloaded the whole repo and executed it just like that, without even touching the code.

Btw its me whose pronounciation you had nailed... Anushtubh

Umm, so what now? @RedHenDev

**Comment by HeyItsAnushtubh** [comment] 2021-07-28 10:00
Are u even gonna respond?

**Comment by RedHenDev** [comment] 2021-07-28 10:43
Hmmmm this is a strange one. Sorry about the slow response -- I don't check issues on here -- although it's a good idea, since we have room to paste code and images :) Much easier than Youtube.

So, I tried running the tut7 code, and it behaved as expected on my machine. Perhaps, then, there's a problem with the version of Ursina on your machine?

![Screenshot 2021-07-28 at 11 41 22](https://user-images.githubusercontent.com/24874180/127309445-ef22ba63-11ff-4191-945c-c41670e3120b.png)

You can check your version by typing `pip freeze` in the terminal. This will list your installed python modules.

**Comment by HeyItsAnushtubh** [comment] 2021-07-28 11:00
@RedHenDev OMG i didnt even think of that!
i had version 3.6.0, so downrgraded and works perfectly now :)
Thanks man!

Also, maybe you tell this in the next tutorial :)

**Comment by HeyItsAnushtubh** [comment] 2021-07-28 11:05
![image](https://user-images.githubusercontent.com/87482637/127312332-da9f33c8-32ff-400a-a769-a304fc91e8e2.png)
cool!

**Comment by RedHenDev** [comment] 2021-07-28 11:18
Oh wow! Can't believe it was just that.

Bad news for the 3.6.0 update, though... :|

Thanks for raising this. Will definitely have to solve since most new users will have 3.6.0!

**Comment by HeyItsAnushtubh** [comment] 2021-07-30 10:02
@RedHenDev Thanks for taking the issue to the Devs. Well now the terrain works fine, but it doesnt have the block texture to it:
![image](https://user-images.githubusercontent.com/87482637/127637124-734ce30d-3e49-4f32-98b5-e6dc4743e35f.png)

**Comment by RedHenDev** [comment] 2021-07-30 10:56
Thanks for the info, buddy -- really helpful.

Try [this]( https://github.com/RedHenDev/python/blob/master/ursina%20dev/tutorials/python_minecraft_tut_2021/pyCraft_model_ISSUE_debug.py).

Looks like we can safely use 3.6.0 now. The issue appears to be with load_model(). Basically, if we load our models via the Entity() call, instead of using load_model(), the issue is solved. I *think* the load_model() was actually loading in a mesh in a very different way. I had thought they were the same!

Anyway -- do let me know if this solves it more satisfactorily :)

**Comment by HeyItsAnushtubh** [comment] 2021-07-30 11:10
The blocks load up correctly, but there's no texture :(
3.6.0 execution :
![image](https://user-images.githubusercontent.com/87482637/127644599-b27b1065-0455-470d-b21f-163838226702.png)

And now 3.5.0 execution:
![image](https://user-images.githubusercontent.com/87482637/127644684-f8a7e5df-4838-49db-94fb-18d8ca846c4a.png)

**Comment by RedHenDev** [comment] 2021-07-30 11:15
OK -- I've found solution! Sorry. I needed to also load in the texture and give each subset and megabit its own texture -- presumably for uv mapping. Have tested on 3.6.0 and seems to work! Give it a go :D

**Comment by HeyItsAnushtubh** [comment] 2021-07-30 11:25
yay! it worked lets go! oh boy..... I can finally close this isssue?

**Comment by HeyItsAnushtubh** [comment] 2021-07-30 11:26
Should i close this issue

**Comment by RedHenDev** [comment] 2021-07-30 11:30
Amazing work, bud!

Yeah, you can close it :D

OMG we were just like a real dev team or something.

**Comment by HeyItsAnushtubh** [comment] 2021-07-30 12:03
You could say that, but i am just 13 year old programming noob or something like that so... yea.
also, I was no help at all, i just kept giving u issues man, so sorry for that :`D 
Ok ill close it,
Great work Brain!
GoodBye (for now XD)

**Comment by HeyItsAnushtubh** [comment] 2021-07-30 12:05
I reopend this i wanna see ur goodbye here :sweat_smile:

**Comment by HeyItsAnushtubh** [comment] 2021-07-30 12:06
I cant keep editing my comment can I

**Comment by RedHenDev** [comment] 2021-07-30 13:25
Lol Goodbye, Anush.

P.s. And yes -- you were incredibly helpful and professional. Thanks again!

**Closed by RedHenDev** 2021-07-30 13:25 UTC
